# Generated by Django 5.0.4 on 2024-04-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='nome',
            new_name='name',
        ),
    ]
